# Generated by Django 3.0.2 on 2020-01-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='fasten_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoecolor',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Indigo', 'Indigo'), ('Violet', 'Violet'), ('White', 'White'), ('Black', 'Black')], default='Green', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoetype',
            name='style',
            field=models.CharField(choices=[('sneaker', 'sneaker'), ('boot', 'boot'), ('sandal', 'sandal'), ('dress', 'dress'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
